#!/usr/bin/env sh

alias sudo="sudo "
alias setsid="setsid -w "

alias open="xdg-open"
alias o="<"
alias se="sudoedit"
alias e="nvim"

alias refresh="exec -l zsh"

alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'
alias dottig='GIT_DIR=$HOME/.dotfiles GIT_WORK_TREE=$HOME tig'

alias -s git="git clone --depth 1"
alias -s {ape,avi,flv,m4a,mkv,mov,mp3,mp4,mpeg,mpg,ogg,ogm,wav,webm}=mpv
alias -s {jpg,jpeg,png,mng,tiff,tif,xpm}=$XIVIEWER
alias -s {htm,html,de,org,net,com,at,cx,nl,se,dk}=$BROWSER
alias -s {cpp,cxx,cc,c,hh,h,inl,asc,md,txt,TXT,tex,conf,config}=nvim
alias -s py="python"
alias -s pdf="zathura"
alias -s gif="$XIVIEWER -a"

alias cp="cp -i"
alias df='df -h'
alias free='free -m'
alias ls='exa -1 --group-directories-first'
alias ll='exa -l --git --group-directories-first'
alias la='exa -la --git --group-directories-first'

alias pac="sudo pacman -Sy --needed --noconfirm"
alias pacs="pacman -Sys"
alias pacy="sudo pacman -Sy"
alias pacyu="sudo pacman -Syu"
alias pacr="sudo pacman -R"
alias pacrns="sudo pacman -Rns"

alias aur="yay -S --needed --noconfirm"
alias aurs="yay -Ss"
alias aury="yay -Sy"
alias auryu="yay -Syu --devel"
alias auryun="yay -Syu --devel --noconfirm"
alias aurr="yay -R"
alias aurrns="yay -Rns --noconfirm"

alias aria="aria2c -x8 --allow-overwrite"
alias cn="ping -c 2 google.com"
alias fan="cat -p /proc/acpi/ibm/fan"
alias c.="code . && exit"

alias yaourt="yay"
alias hc="sudo hostctl"
alias sv="sudo sv"
