#!/usr/bin/env sh

alias sudo="sudo "
alias setsid="setsid "

alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'

# Files
alias zshrc="$EDITOR $HOME/.config/zsh/.zshrc"
alias profile="$EDITOR $HOME/.profile"
alias aliasrc="$EDITOR $HOME/.config/aliasrc"
alias securealiasrc="$EDITOR $HOME/.config/securealiasrc"
alias dwmrc="$EDITOR $HOME/build/dwm/config.h"
alias strc="$EDITOR $HOME/build/st-flexipatch/config.h"
alias lfrc="$EDITOR $HOME/.config/lf/lfrc"
alias xinitrc="$EDITOR $HOME/.xinitrc"
alias ncmrc="$EDITOR $HOME/.config/ncmpcpp/config"
alias mpvrc="$EDITOR $HOME/.config/mpv/mpv.conf"
alias mpvinp="$EDITOR $HOME/.config/mpv/input.conf"
alias mimerc="$EDITOR $HOME/.config/mimi/mime.conf"
alias sxhkdrc="$EDITOR $HOME/.config/sxhkd/sxhkdrc"
alias zathurarc="$EDITOR $HOME/.config/zathura/zathurarc"
alias pistolrc="$EDITOR $HOME/.config/pistol/pistol.conf"
alias dunstrc="$EDITOR $HOME/.config/dunst/dunstrc"
alias lsrc="$EDITOR $HOME/.config/LS_COLORS"
alias zplugins="$EDITOR $HOME/.config/zsh/.zshplugins"

alias ngen="$EDITOR $HOME/.config/nvim/config/general.vimrc"
alias nkey="$EDITOR $HOME/.config/nvim/config/keys.vimrc"
alias nplg="$EDITOR $HOME/.config/nvim/config/plugins.vimrc"
alias nfun="$EDITOR $HOME/.config/nvim/config/functions.vimrc"

alias n="$EDITOR"
alias o="<"
alias :q="exit"

alias -s {ape,avi,flv,m4a,mkv,mov,mp3,mp4,mpeg,mpg,ogg,ogm,wav,webm}=mpv
alias -s {jpg,jpeg,png,mng,tiff,tif,xpm}=$XIVIEWER
alias -s {htm,html,de,org,net,com,at,cx,nl,se,dk}=$BROWSER
alias -s {cpp,cxx,cc,c,hh,h,inl,asc,md,txt,TXT,tex,conf,config}=nvim
alias -s pdf="zathura"
alias -s gif="$XIVIEWER -a"

alias fuck='sudo $(fc -ln -1)'
alias refresh="source $HOME/.config/zsh/.zshrc && source $HOME/.profile"

alias dwmmake="cd ~/build/dwm/ ;sudo make clean install; cd -"
alias stmake="cd ~/build/st-flexipatch/; sudo make clean install; cd -"

alias ls='exa -1 --group-directories-first'
alias ll='exa -l --git --group-directories-first'
alias la='exa -la --git --group-directories-first'
alias ping="prettyping"

alias pac="sudo pacman -S --needed"
alias pacs="sudo pacman -Ss"
alias pacy="sudo pacman -Sy"
alias pacyu="sudo pacman -Syu"
alias pacr="sudo pacman -R"
alias pacrns="sudo pacman -Rns"

alias aur="yay -S --needed --noconfirm"
alias aurs="yay -Ss"
alias aury="yay -Sy"
alias auryu="yay -Syu --devel"
alias auryun="yay -Syu --devel --noconfirm"
alias aurr="yay -R"
alias aurrns="yay -Rns"

alias batt="acpi -b"
alias aria="aria2c -x8 --allow-overwrite"
alias connected="ping -c 2 google.com"
alias connectedn="nmtui-connect"
alias fan-status="bat -p /proc/acpi/ibm/fan"
alias c="code"
alias peerflix="peerflix -kd"
alias ncm="ncmpcpp"
alias ffrec="ffmpeg -y -f x11grab -s 1366x768 -i :0.0 out.mkv"
alias screenshottoclipboard="import png:- | xclip -selection clipboard -t image/png"
alias rename-2-kebabcase="node ~/build/rename-2-kebabcase/index.js"
alias ascii="< ~/build/ascii | dmenu -l 30 | awk \'{print $2}\'"


alias yamete="docker run --rm -ti -v ~/media/books/.x:/app/downloads -u 1000:1000 jaymoulin/yamete download -p -u"
alias yamete-list="docker run --rm -ti -v ~/media/books/.x:/app/downloads -v ~/.buffers/yamete:/app/list -u 1000:1000 jaymoulin/yamete download -p -l /app/list"
alias yamete-load='echo $(xclip -selection primary -o) >> ~/.buffers/yamete'

alias 4chan="~/build/4chan-downloader/inb4404.py -cdln"
alias glow="glow -s dark"
